In [1]:
import numpy as np

In [2]:
lending_data = np.genfromtxt('Lending-Company-Numeric-Data-NAN.csv' , delimiter=';', skip_header=2) #here skip_header will skip first 2 rows of the data
lending_data

array([[ 1000.,    40.,   365.,  2160.,  3280., 15340.],
       [ 2000.,    40.,   365.,  3041.,  4241., 15321.],
       [ 2000.,    50.,   365.,  3470.,  4820., 13720.],
       ...,
       [   nan,    40.,   365.,  4201.,  5001., 16600.],
       [ 1000.,    40.,   365.,  2080.,  3320., 15600.],
       [ 2000.,    40.,   365.,  4601.,  4601., 16600.]])

In [5]:
lending_data_footer = np.genfromtxt('Lending-Company-Numeric-Data-NAN.csv' , delimiter=';', skip_footer=2) #here skip_footer will skip last 2 rows of the data
lending_data_footer

array([[  40.,  365., 3121.],
       [  40.,  365., 3061.],
       [  40.,  365., 2160.],
       ...,
       [  40.,  365., 4201.],
       [  40.,  365., 2080.],
       [  40.,  365., 4601.]])

In [14]:
lending_data_col = np.genfromtxt('Lending-Company-Numeric-Data-NAN.csv' , delimiter=';', usecols=(0, 1, 4,5) ) #here skip_header will skip first 2 rows of the data
lending_data_col

array([[ 2000.,    40.,  4241., 13621.],
       [ 2000.,    40.,  4171., 15041.],
       [ 1000.,    40.,  3280., 15340.],
       ...,
       [   nan,    40.,  5001., 16600.],
       [ 1000.,    40.,  3320., 15600.],
       [ 2000.,    40.,  4601., 16600.]])