In [1]:
import numpy as np

In [2]:
s = 5

In [3]:
s

5

In [4]:
v = np.array([5, -3, 6])

In [5]:
v

array([ 5, -3,  6])

In [7]:
m = np.array([[5, 12, 6], [-3, 0, 14]])

In [8]:
m

array([[ 5, 12,  6],
       [-3,  0, 14]])

In [9]:
type(s)

int

In [10]:
type(v)

numpy.ndarray

In [11]:
type(m)

numpy.ndarray

In [12]:
sArray = np.array(5)

In [13]:
sArray

array(5)

In [14]:
m.shape

(2, 3)

In [17]:
v.shape

(3,)

In [25]:
v.reshape(1, 3) 

array([[ 5, -3,  6]])

In [20]:
sArray.reshape

<function ndarray.reshape>

In [21]:
sArray.shape

()

In [22]:
v1 = np.array([1, 2, 3])

In [23]:
print(v+v1)

[ 6 -1  9]


In [26]:
v1.T

array([1, 2, 3])

In [27]:
v1

array([1, 2, 3])