In [1]:
import numpy as np

In [2]:
array_empty = np.empty(shape = (2, 3))

In [3]:
array_empty

array([[0., 0., 0.],
       [0., 0., 0.]])

In [4]:
arrays_0s = np.zeros(shape=(2, 3))
arrays_0s

array([[0., 0., 0.],
       [0., 0., 0.]])

In [5]:
arrays_1s = np.ones(shape=(2, 3))
arrays_1s

array([[1., 1., 1.],
       [1., 1., 1.]])

In [6]:
arrays_full = np.full(shape=(2, 3), fill_value=3)
arrays_full

array([[3, 3, 3],
       [3, 3, 3]])

# like_ function

In [7]:
matrixA = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10], [11, 12, 13, 14, 15]])
matrixA

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [13]:
empty_arr = np.empty_like(matrixA)
empty_arr

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [14]:
arr_0s_like = np.zeros_like(matrixA)
arr_0s_like 

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

# np.arange() function

In [15]:
list(range(30))

[0,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29]

In [21]:
aran = np.arange(1, 31, 4)
aran

array([ 1,  5,  9, 13, 17, 21, 25, 29])

# Random Generator 

In [23]:
from numpy.random import Generator as gen
from numpy.random import PCG64 as pcg

In [39]:
array_RG = gen(pcg()) 
array_RG.normal(size = 121)

array([ 0.15539272, -0.77083612, -0.53576838, -0.19507873, -1.11294947,
        1.15487918, -2.32623297,  1.29034127, -0.80494228, -0.43664474,
       -0.60744584,  0.43968209, -0.86836282, -1.69128344,  0.05229368,
        1.06060539, -0.80937725,  0.66401552,  0.65045704, -0.32673453,
        1.33910184, -1.10619105, -0.55389931, -0.14246693,  0.89570879,
       -0.230194  , -0.4611072 ,  0.8760837 ,  1.10294842, -0.65309651,
        1.36270229, -0.72328918,  0.54933836,  0.33694791, -0.13676424,
       -1.31015119,  0.70502976, -0.26644306, -1.31183972,  0.3215144 ,
       -0.82682539, -0.91667062,  0.38333581,  1.0986422 ,  1.52760646,
       -1.18885515, -0.72405747, -2.81887405, -0.05983384,  0.79116618,
        1.2320946 ,  1.35565326, -1.95911705,  0.21714372, -0.78571781,
        0.59622807, -0.31484115,  0.18397876,  1.37017007, -1.72172465,
        0.84257404,  1.10732452,  0.82244404, -0.5565548 , -1.60423225,
        0.62014813,  0.75398768, -0.68789844, -0.19762277,  1.24

In [43]:
array_RG.integers(100, size=(5,5))

array([[84, 52, 84, 77, 45],
       [ 9, 56,  5, 16, 33],
       [13, 39, 22, 16, 30],
       [68, 70, 37, 57, 31],
       [17, 63, 61, 53, 19]])