In [1]:
import numpy as np

In [2]:
m1 = np.array([[1, 2, 3], [4, 5, 6]])

In [3]:
m1

array([[1, 2, 3],
       [4, 5, 6]])

In [4]:
m2 = np.array([[11, 12, 13], [21, 22, 23]])


In [5]:
m2

array([[11, 12, 13],
       [21, 22, 23]])

In [6]:
t = np.array([m1,m2])

In [7]:
t

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[11, 12, 13],
        [21, 22, 23]]])

In [8]:
t.shape

(2, 2, 3)

In [9]:
print(m1+m2)

[[12 14 16]
 [25 27 29]]


In [11]:
print(m2-m1)

[[10 10 10]
 [17 17 17]]


In [12]:
t.T

array([[[ 1, 11],
        [ 4, 21]],

       [[ 2, 12],
        [ 5, 22]],

       [[ 3, 13],
        [ 6, 23]]])

In [13]:
v = np.array([1, 2, 3])
u=np.array([4, 5, 6])


In [14]:
print(np.dot(v,u))

32


In [16]:
print(u*4)

[16 20 24]


In [18]:
print(np.dot(m1, m2.T))

[[ 74 134]
 [182 332]]
