In [1]:
import numpy as np

# np.mean()

In [2]:
mat_A = np.array([[1, 0, 0, 3, 1], [3, 6, 6, 2, 9], [4, 5, 3, 8, 0]])
mat_A

array([[1, 0, 0, 3, 1],
       [3, 6, 6, 2, 9],
       [4, 5, 3, 8, 0]])

In [3]:
np.mean(mat_A) #mean of the while data 

3.4

In [4]:
np.mean(mat_A[0]) # for first row of the matrix

1.0

In [5]:
np.mean(mat_A[:, 0]) # for first column of the matrix

2.6666666666666665

In [6]:
np.mean(mat_A, axis=0) # the axis , argument helps us to calculate the mean of single column 

array([2.66666667, 3.66666667, 3.        , 4.33333333, 3.33333333])

In [7]:
np.mean(mat_A, axis=1) # changing the value of axis from zero to one will calculate the mean for single row and return it in array

array([1. , 5.2, 4. ])

# Min and Max Values 

In [11]:
mat_B = np.array([[2, 5, 6, 1, 3], [3, 8, 2, 0, -1], [9, 2, 1, 8, 4]])
mat_B

array([[ 2,  5,  6,  1,  3],
       [ 3,  8,  2,  0, -1],
       [ 9,  2,  1,  8,  4]])

In [12]:
np.min(mat_B)

-1

In [13]:
mat_A

array([[1, 0, 0, 3, 1],
       [3, 6, 6, 2, 9],
       [4, 5, 3, 8, 0]])

# Statistical Order Functions

In [14]:
np.ptp(mat_A)

9

In [15]:
np.max(mat_A)

9

In [16]:
np.ptp(mat_A, axis=0)

array([3, 6, 6, 6, 9])

In [17]:
np.ptp(mat_B, axis=1)

array([5, 9, 8])

In [20]:
np.quantile(mat_A, 0.70, interpolation="nearest")

5

# Average and Variance in Numpy

In [23]:
np.median(mat_A, )

3.0

In [27]:
np.sort(mat_A, axis=None)

array([0, 0, 0, 1, 1, 2, 3, 3, 3, 4, 5, 6, 6, 8, 9])

In [28]:
np.mean(mat_A)

3.4

In [29]:
np.average(mat_A)

3.4

In [30]:
from numpy.random import Generator as gen
from numpy.random import PCG64 as pcg

array_rg = gen(pcg(365))
array_weight = array_rg.random(size=(3, 5))
array_weight

array([[0.75915734, 0.7662218 , 0.6291028 , 0.20336599, 0.66501486],
       [0.06559111, 0.71326309, 0.10812106, 0.87969046, 0.49405844],
       [0.82472673, 0.45652944, 0.07367232, 0.69628564, 0.36690736]])

In [31]:
np.average(mat_A, weights=array_weight)

3.2120290871899306

In [32]:
np.var(mat_A)

7.84

In [33]:
np.std(mat_A)

2.8

In [34]:
2.8**2

7.839999999999999