In [1]:
import pandas as pd
import numpy as np

In [2]:
price_per_cat = pd.Series({'Product_A': 22250, 'Product_B': 45632, 'Product_C': 89872})
price_per_cat

Product_A    22250
Product_B    45632
Product_C    89872
dtype: int64

In [3]:
price_per_cat.values #this method will combine the values of the key in an array

array([22250, 45632, 89872])

In [4]:
type(price_per_cat)

pandas.core.series.Series

In [5]:
price_per_cat.array

<NumpyExtensionArray>
[22250, 45632, 89872]
Length: 3, dtype: int64

In [6]:
price_per_cat.to_numpy() #This method also combine the values of the key to an array

array([22250, 45632, 89872])

In [7]:
type(price_per_cat.to_numpy())

numpy.ndarray

In [9]:
test_array = price_per_cat[['Product_A', 'Product_B']].to_numpy(dtype='float')
test_array

array([22250., 45632.])