In [1]:
import numpy as np

In [3]:
array_a = np.array([[1, 2, 3], [4, 5, 6]])
array_a

array([[1, 2, 3],
       [4, 5, 6]])

In [4]:
type(array_a)

numpy.ndarray

In [5]:
array_a[0]

array([1, 2, 3])

In [6]:
array_a[0,1]

2

In [7]:
array_a[1,0]

4

In [9]:
array_a[:, 2]

array([3, 6])

In [10]:
array_b = np.array([1, 2, 3])
array_b[-1]

3

In [11]:
array_b[-2]

2

# #Assigning Values to the array

In [12]:
array_a[0,2] = 9

In [13]:
array_a

array([[1, 2, 9],
       [4, 5, 6]])

In [14]:
array_a[0]=9


In [15]:
array_a[:,0]=9

In [16]:
array_a

array([[9, 9, 9],
       [9, 5, 6]])

In [17]:
list_a = [8, 7, 8]
array_a[0] = list_a
array_a

array([[8, 7, 8],
       [9, 5, 6]])

In [18]:
array_a[:] =9
array_a

array([[9, 9, 9],
       [9, 9, 9]])

In [19]:
array_a = 9
type(array_a)

int

# Elementwise Properties

In [21]:
array_a = np.array([7, 8, 9])
array_a

array([7, 8, 9])

In [22]:
array_b = np.array([[1, 2, 3],[4,5,6]])
array_b

array([[1, 2, 3],
       [4, 5, 6]])

In [23]:
array_a+2

array([ 9, 10, 11])

In [24]:
array_b * 2

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [26]:
array_a + array_b[1]

array([11, 13, 15])

In [28]:
array_a * array_b

array([[ 7, 16, 27],
       [28, 40, 54]])

In [32]:
array_a = np.array([[1, 2, 3],[4, 5, 6]], dtype = np.float32 )
array_a

array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)

In [33]:
array_a = np.array([[1, 2, 3],[4, 5, 6]], dtype = np.complex64 )
array_a

array([[1.+0.j, 2.+0.j, 3.+0.j],
       [4.+0.j, 5.+0.j, 6.+0.j]], dtype=complex64)

In [37]:
array_a = np.array([[1, 2, 0],[4, 0, 6]], dtype = np.bool_)
array_a

array([[ True,  True, False],
       [ True, False,  True]])

In [40]:
array_a = np.array([[1, 22, 3],[4, 5, 6]], dtype = np.str_ )
array_a

array([['1', '22', '3'],
       ['4', '5', '6']], dtype='<U2')

# Characteristics of Numpy Functions

# Universal Functions

Broadcasting

In [41]:
array_a = np.array([1, 2, 3])
array_a

array([1, 2, 3])

In [42]:
array_b = np.array([[1], [2]])
array_b

array([[1],
       [2]])

In [43]:
matrix_c = np.array([[1, 2, 3], [4, 5, 6]])
matrix_c

array([[1, 2, 3],
       [4, 5, 6]])

In [45]:
np.add(array_a, matrix_c)

array([[2, 4, 6],
       [5, 7, 9]])

TypeCasting

In [48]:
np.add(array_b, matrix_c, dtype = np.float64)

array([[2., 3., 4.],
       [6., 7., 8.]])

# Running Over an Axis

In [51]:
np.mean(matrix_c, axis = 0)

array([2.5, 3.5, 4.5])